Repository Darkrp-community/OpenKeep, pull requests merged in 2024-09, with the labels that each got.

#595 Bowclicking
  icons/roguetown/weapons/32.dmi
  icons/roguetown/weapons/ammo.dmi
Labels: Scheduled for testmerge, Icons

#622 Sack Emptying Fix
  code/datums/components/storage/storage.dm
Labels: Bugfix

#627 Fixes smithed weapons losing their Wdefense modifier when Wielded and then Unwielded.
  code/game/objects/items.dm
Labels: Bugfix

#615 Mercenary <3 Merchant
  _maps/map_files/dun_manor/dun_manor.dmm
  code/game/objects/items/rogueitems/keyrings.dm
  code/game/objects/structures/crates_lockers/roguetown.dm
  code/modules/jobs/job_types/roguetown/other/mercenary.dm
  code/modules/mob/living/simple_animal/hostile/roguetown/haunt.dm
  code/modules/reagents/reagent_containers/powderspice.dm
  code/modules/roguetown/roguemachine/drugmachine.dm
  stonekeep.dme
Labels: Scheduled for testmerge, Map

#640 Allowing Towners to Play Back-to-Back
  code/modules/jobs/job_types/roguetown/adventurer/villager.dm
Labels: Scheduled for testmerge

#604 VL mode pop limit port
  code/game/gamemodes/roguetown/roguetown.dm
Labels: Scheduled for testmerge

#605 Ports Hearthstone Delimb Changes
  code/game/objects/items/rogueweapons/rogueweapon.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/mob_defines.dm
Labels: Scheduled for testmerge

#621 Allows Dwarf Niteman/matron/maiden
  code/modules/clothing/rogueclothes/shirts.dm
  code/modules/jobs/job_types/roguetown/nobility/nightman.dm
  code/modules/jobs/job_types/roguetown/peasants/bathmaid.dm
Labels: Scheduled for testmerge

#650 Centcomm mapping (from 562)
  _maps/custom/roguehamlet.dmm
  _maps/custom/stonekeep.dmm
  _maps/map_files/backup2/roguetown.dmm
  _maps/map_files/dakkatown/dakkatown.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/map_files/roguetown/old/roguetown.dmm
  _maps/map_files/roguetown/otherz/roguehamlet.dmm
  _maps/map_files/rogueworld/roguetown.dmm
  _maps/roguehamlet/roguehamlet.dmm
  code/game/area/roguetownareas.dm
  code/game/objects/structures/beds_chairs/roguechair.dm
  code/game/objects/structures/crates_lockers/roguetown.dm
  code/game/objects/structures/fluff.dm
  code/game/objects/structures/roguetent.dm
  code/game/objects/structures/walldeco.dm
  code/game/turfs/open/floor/roguefloor.dm
  code/modules/cargo/packsrogue/luxury.dm
  code/modules/reagents/reagent_containers/powderspice.dm
  code/modules/roguetown/roguecrafting/items.dm
  code/modules/roguetown/roguecrafting/structure.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/tools.dm
  icons/roguetown/misc/structure.dmi
  modular/Mapping/Mapping_aides.dm
Labels: Map

#652 Knight Crests
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/armor.dm
  icons/roguetown/clothing/head.dmi
  icons/roguetown/clothing/onmob/64x64/head.dmi
Labels: Icons

#562 Spicebug Fix, Bandits, Butter
  code/__DEFINES/roguetown.dm
  code/game/objects/effects/decals/cleanable/food.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/storage/bags.dm
  code/modules/antagonists/roguetown/villain/bandit.dm
  code/modules/antagonists/roguetown/villain/zizocult.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/food_and_drinks/food/snacks_egg.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/bandit.dm
  code/modules/mob/living/carbon/status_procs.dm
  code/modules/power/roguelighting.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/roguetown/roguejobs/cook/tools/pot.dm
  icons/roguetown/items/cooking.dmi
  icons/roguetown/items/produce.dmi
  modular/Mapping/icons/decoration.dmi
  modular/Neu_Food/code/NeuFood.dm
  modular/Neu_Food/code/cooked/NeuFood_meals.dm
  modular/Neu_Food/code/cooked/NeuFood_pies.dm
  modular/Neu_Food/code/cooked/NeuFood_snacks.dm
  modular/Neu_Food/code/raw/NeuFood_dough.dm
  modular/Neu_Food/code/raw/NeuFood_meat.dm
  modular/Neu_Food/code/raw/NeuFood_processed.dm
  modular/Neu_Food/icons/cooking.dmi
  modular/Neu_Food/icons/food.dmi
Labels: Scheduled for testmerge, Map, Bugfix

#623 Zybantine Perfumes
  _maps/map_files/dun_manor/dun_manor.dmm
  code/datums/components/pollutant.dm
  code/datums/pollutant.dm
  code/datums/stress/positive_events.dm
  code/game/objects/items/rogueitems/perfume.dm
  code/game/turfs/open/pollutants.dm
  code/modules/cargo/packsrogue/luxury.dm
  icons/roguetown/items/perfume.dmi
  sound/items/perfume.ogg
  stonekeep.dme
Labels: Map, Icons, New features

#663 Fixes an issue with Pestran acolytes not spawning with any actual miracles or outfit. Fixes an issue with clerics spawning with armor they are not proficient with, gives them chainmail shirt instead for identical coverage.
  code/datums/gods/patrons/divine_pantheon.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
  code/modules/jobs/job_types/roguetown/church/monk.dm
Labels: Ready to merge, Bugfix

#664 fix arrows
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
Labels: Bugfix

#668 [FIX] Thick Eyebrow Sidesprite Fix
  icons/roguetown/mob/detail.dmi
Labels: Icons, Bugfix

#677 Perfume hotfix
  code/datums/pollutant.dm
Labels: Bugfix

#667 You now perma-die slower when in bloodloss crit
  code/modules/mob/living/blood.dm
  code/modules/mob/living/carbon/human/life.dm
Labels: Scheduled for testmerge

#644 Copper updates
  _maps/map_files/generic/CentCom.dmm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/rogueweapons/melee/axes.dm
  code/game/objects/items/rogueweapons/melee/blunt.dm
  code/game/objects/items/rogueweapons/melee/knives.dm
  code/game/objects/items/rogueweapons/melee/polearms.dm
  code/game/objects/items/rogueweapons/melee/swords.dm
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/mask.dm
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/clothing/rogueclothes/wrists.dm
  code/modules/jobs/job_types/roguetown/apprentices/squire.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/armor.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/tools.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
  code/modules/roguetown/roguejobs/blacksmith/tools.dm
  code/modules/roguetown/roguejobs/farmer/tools.dm
  code/modules/roguetown/roguejobs/miner/tools.dm
  icons/roguetown/clothing/armor.dmi
  icons/roguetown/clothing/head.dmi
  icons/roguetown/clothing/masks.dmi
  icons/roguetown/clothing/neck.dmi
  icons/roguetown/clothing/onmob/armor.dmi
  icons/roguetown/clothing/onmob/belt_l.dmi
  icons/roguetown/clothing/onmob/belt_r.dmi
  icons/roguetown/clothing/onmob/head.dmi
  icons/roguetown/clothing/onmob/masks.dmi
  icons/roguetown/clothing/onmob/neck.dmi
  icons/roguetown/clothing/onmob/wrists.dmi
  icons/roguetown/clothing/wrists.dmi
  icons/roguetown/items/lighting.dmi
  icons/roguetown/weapons/32.dmi
  icons/roguetown/weapons/64.dmi
  icons/roguetown/weapons/tools.dmi
Labels: Map, Icons

#628 Nets
  code/__DEFINES/movespeed_modification.dm
  code/datums/status_effects/rogue/debuff.dm
  code/game/objects/items/rogueitems/ropechainbola.dm
  code/modules/cargo/packsrogue/weapons.dm
  code/modules/roguetown/roguecrafting/items.dm
  icons/roguetown/items/misc.dmi
  icons/roguetown/mob/bodies/cuffed.dmi
Labels: Scheduled for testmerge, Icons, New features

#608 Combatant Butterfinger Remover (now with 20% more tripping)
  code/modules/mob/living/living.dm
Labels: Bugfix

#529 Opens up Barbarians to women and a few races, Rage ability
  code/datums/status_effects/rogue/debuff.dm
  code/datums/status_effects/rogue/roguebuff.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/barbarian.dm
  code/modules/spells/roguetown/acolyte/general.dm
  sound/magic/barbroar.ogg
Labels: Scheduled for testmerge, Squash me

#633 Forest and MT decap remapping, Bug fixing
  _maps/map_files/roguetown/otherz/smalldecap.dmm
  _maps/map_files/roguetown/otherz/smallforest.dmm
Labels: Map

#673 Second wave Maid / Servant QOL gaming
  _maps/map_files/dun_manor/dun_manor.dmm
  code/game/objects/items/rogueitems/keyrings.dm
  code/modules/jobs/job_types/roguetown/apprentices/servant.dm
  code/modules/jobs/job_types/roguetown/peasants/butler.dm
Labels: Map

#579 Ports Ratwood's "Charge and Sprint changes"
  code/modules/mob/living/living.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_movement.dm
Labels: Scheduled for testmerge

#703 Zizoid Cultist Ritual Meat Requirement Fix
  code/modules/antagonists/roguetown/villain/zizocult.dm
Labels: Bugfix

#705 New Tiefling Hair Colors
  code/modules/mob/living/carbon/human/species_types/roguetown/other/tiefling.dm
Labels: Icons

#694 Paladin, Paladin, where do you roam
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/donator/templar.dm
Labels: Bugfix

#708 Fixes Longbeard Hammer (Balance, Bugfix)
  _maps/map_files/dakkatown/dakkatown.dmm
  _maps/map_files/generic/CentCom.dmm
  code/game/objects/items/rogueweapons/melee/blunt.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/donator/longbeard.dm
  code/modules/mob/living/carbon/human/npc/orc.dm
Labels: Map, Bugfix

#641 Mercenary Tokens
  code/modules/cargo/packsrogue/luxury.dm
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/jobs/job_types/roguetown/nobility/merchant.dm
  code/modules/jobs/job_types/roguetown/other/merc_classes/blackoak.dm
  code/modules/jobs/job_types/roguetown/other/merc_classes/boltslinger.dm
  code/modules/jobs/job_types/roguetown/other/merc_classes/grenzelhoft.dm
  code/modules/jobs/job_types/roguetown/other/merc_classes/underdweller.dm
  code/modules/jobs/job_types/roguetown/other/merc_classes/zybantine.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/paperwork/rogue.dm
  code/modules/roguetown/roguemachine/mail.dm
  icons/roguetown/clothing/neck.dmi
  icons/roguetown/clothing/onmob/neck.dmi
  icons/roguetown/items/misc.dmi
  sound/misc/mercsuccess.ogg
Labels: Scheduled for testmerge, Icons, New features

#617 Hair overhaul
  code/modules/mob/dead/new_player/sprite_accessories.dm
  icons/roguetown/mob/hair.dmi
  icons/roguetown/mob/hair_extensions.dmi
Labels: Scheduled for testmerge, Icons

#692 quick sprite update
  icons/roguetown/weapons/32.dmi
  icons/roguetown/weapons/64.dmi
Labels: Icons

#723 Makes pray visible to admins only
  code/modules/admin/verbs/pray.dm
Labels: Bugfix

#718 Vampire Mine Exhausted, VL discovers he got open windows and fake books. Drama ensues.
  _maps/map_files/generic/CentCom.dmm
  _maps/map_files/old_maps/roguetown2.dmm
  _maps/map_files/old_maps/roguetown3.dmm
  _maps/map_files/old_maps/roguetown4.dmm
  _maps/map_files/old_maps/roguetown5.dmm
  code/game/objects/items/candle.dm
  code/game/objects/structures/beds_chairs/roguechair.dm
  code/game/objects/structures/tables_racks.dm
  modular/Mapping/Mapping_aides.dm
Labels: Map

#656 Combat Stuff: Monk & Rogue's Delight
  code/_onclick/other_mobs.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/grabbing.dm
  code/modules/mob/living/living.dm
  code/modules/surgery/bodyparts/head.dm
  icons/mob/roguehud.dmi
Labels: Scheduled for testmerge, New features

#735 Demotes the swordmaster to hedge knight after repeated failures to bring honor to the Empire.
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/donator/swordmaster.dm
Labels: Unapproved restricted changes

#684 Longer KO time from blunt, only skull and neck crits paralyze.
  code/datums/wounds/fractures.dm
  code/modules/surgery/bodyparts/bodypart_wounds.dm
Labels: Scheduled for testmerge

#681 Sellable organs, with variable price based on stats
  code/modules/jobs/job_types/roguetown/nobility/feldsher.dm
  code/modules/mob/living/stats.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  code/modules/surgery/organs/organ_internal.dm
  code/modules/surgery/organs/tongue.dm
Labels: New features

#758 Eora Surcoats for Cleric and Templar
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
Labels: Scheduled for testmerge

#618 Alchemy System: Those Ones Were Duds But We're For Real Now
  code/game/objects/inhands_rogue.dm
  code/game/objects/items/rogueitems/natural/ash.dm
  code/game/objects/items/rogueitems/natural/dirtclod.dm
  code/modules/hydroponics/grown/roguesmoke.dm
  code/modules/hydroponics/grown/roguetown.dm
  code/modules/jobs/job_types/roguetown/nobility/archivist.dm
  code/modules/jobs/job_types/roguetown/nobility/feldsher.dm
  code/modules/jobs/job_types/roguetown/nobility/magician.dm
  code/modules/mob/living/simple_animal/hostile/roguetown/crow.dm
  code/modules/mob/living/simple_animal/rogue/creacher/mole.dm
  code/modules/mob/living/simple_animal/rogue/creacher/troll.dm
  code/modules/mob/living/simple_animal/rogue/creacher/volf.dm
  code/modules/mob/living/simple_animal/rogue/farm/cow.dm
  code/modules/mob/living/simple_animal/rogue/farm/goat.dm
  code/modules/mob/living/simple_animal/rogue/game/saiga.dm
  code/modules/reagents/reagent_containers/bottle.dm
  code/modules/reagents/reagent_containers/powderspice.dm
  code/modules/roguetown/roguecrafting/alchemy/cauldron.dm
  code/modules/roguetown/roguecrafting/alchemy/ingredients.dm
  code/modules/roguetown/roguecrafting/alchemy/mortarpestle.dm
  code/modules/roguetown/roguecrafting/alchemy/potionbuffs.dm
  code/modules/roguetown/roguecrafting/items.dm
  code/modules/roguetown/roguecrafting/runes.dm
  code/modules/roguetown/roguecrafting/structure.dm
  code/modules/roguetown/roguejobs/alchemist/container.dm
  code/modules/roguetown/roguejobs/alchemist/reagents.dm
  code/modules/roguetown/roguejobs/fisher/fish.dm
  code/modules/roguetown/roguejobs/fisher/leeches.dm
  code/modules/roguetown/roguejobs/miner/rogueores.dm
  icons/roguetown/items/books.dmi
  icons/roguetown/misc/alchemy.dmi
  modular/Neu_Farming/code/chaff.dm
  modular/Neu_Farming/code/produce.dm
  modular/Neu_Farming/code/seeds.dm
  modular/Neu_Food/code/NeuFood.dm
  sound/foley/mortarpestle.ogg
  stonekeep.dme
Labels: Scheduled for testmerge, Squash me, Icons, New features

#769 Murderwood Drifter QOL Changes v2 (Braziers, Bridge, Maneater/Mantrap Reduction)
  _maps/map_files/roguetown/otherz/smallforest.dmm
  code/modules/roguetown/mapgen/forest.dm
Labels: Scheduled for testmerge

#770 Murderwood Drifter QOL Changes v3 (Bandit Camp)
  _maps/map_files/generic/CentCom.dmm
Labels: Scheduled for testmerge

#678 Inquisition Against Merge Conflicts
  _maps/custom/roguehamlet.dmm
  _maps/custom/roguehamlet1.dmm
  _maps/map_files/dun_manor/dun_manor.dmm
  _maps/map_files/roguetown/otherz/roguehamlet.dmm
  _maps/map_files/roguetown/roguetown.dmm
  _maps/roguehamlet/roguehamlet.dmm
  code/__DEFINES/combat.dm
  code/__DEFINES/roguetown.dm
  code/_globalvars/lists/wounds.dm
  code/game/objects/items/rogueitems/keyrings.dm
  code/game/objects/items/rogueitems/keys.dm
  code/game/objects/items/rogueweapons/ranged/ammo.dm
  code/game/objects/items/rogueweapons/ranged/crossbows.dm
  code/game/objects/items/rogueweapons/ranged/flintlock.dm
  code/game/objects/items/rogueweapons/shields.dm
  code/modules/clothing/rogueclothes/cloaks.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/robes.dm
  code/modules/clothing/rogueclothes/storage.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/witchhunter.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rogue.dm
  code/modules/jobs/job_types/roguetown/church/adept.dm
  code/modules/jobs/job_types/roguetown/church/inquisitor.dm
  code/modules/jobs/job_types/roguetown/church/monk.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
  code/modules/jobs/job_types/roguetown/garrison/garrisonarcher.dm
  code/modules/jobs/job_types/roguetown/garrison/garrisonguard.dm
  code/modules/jobs/job_types/roguetown/garrison/royalguard.dm
  code/modules/jobs/job_types/roguetown/nobility/captain.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/living_defense.dm
  code/modules/paperwork/rogue.dm
  code/modules/reagents/chemistry/reagents/roguetown.dm
  code/modules/reagents/reagent_containers/powderspice.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
  code/modules/roguetown/roguemachine/mail.dm
  code/modules/surgery/bodyparts/bodypart_wounds.dm
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/roguetown/clothing/head.dmi
  icons/roguetown/clothing/onmob/head.dmi
  icons/roguetown/items/cooking.dmi
  icons/roguetown/items/misc.dmi
  icons/roguetown/items/produce.dmi
  icons/roguetown/weapons/32.dmi
  sound/combat/Ranged/muskclick.ogg
  sound/combat/Ranged/muskshoot.ogg
  sound/foley/gun_drop.ogg
  sound/foley/gun_equip.ogg
  sound/foley/gunpowder_fill.ogg
  sound/foley/tinnitus.ogg
  sound/foley/winding.ogg
  stonekeep.dme
Labels: Scheduled for testmerge, Map, Squash me, Icons, New features

#707 Troll Update
  code/modules/antagonists/roguetown/villain/zizocult.dm
  code/modules/jobs/job_types/roguetown/garrison/garrisonguard.dm
  code/modules/mob/living/simple_animal/rogue/creacher/troll.dm
  code/modules/mob/living/simple_animal/rogue/creacher/trollbog.dm
  code/modules/mob/living/simple_animal/rogue/creacher/zizoid.dm
  icons/roguetown/mob/monster/Trolls.dmi
  stonekeep.dme
Labels: Scheduled for testmerge, Icons

#742 Dark Elf mercenary with subclasses, Whip intent tweaks
  code/game/objects/items/rogueweapons/melee/whips.dm
  code/game/objects/items/rogueweapons/shields.dm
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/cloaks.dm
  code/modules/clothing/rogueclothes/gloves.dm
  code/modules/clothing/rogueclothes/mask.dm
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/clothing/rogueclothes/pants.dm
  code/modules/clothing/rogueclothes/shirts.dm
  code/modules/jobs/job_types/roguetown/other/merc_classes/anthrax.dm
  code/modules/roguetown/roguemachine/mail.dm
  icons/roguetown/clothing/armor.dmi
  icons/roguetown/clothing/cloaks.dmi
  icons/roguetown/clothing/gloves.dmi
  icons/roguetown/clothing/masks.dmi
  icons/roguetown/clothing/neck.dmi
  icons/roguetown/clothing/onmob/armor.dmi
  icons/roguetown/clothing/onmob/cloaks.dmi
  icons/roguetown/clothing/onmob/gloves.dmi
  icons/roguetown/clothing/onmob/helpers/sleeves_armor.dmi
  icons/roguetown/clothing/onmob/helpers/sleeves_pants.dmi
  icons/roguetown/clothing/onmob/masks.dmi
  icons/roguetown/clothing/onmob/pants.dmi
  icons/roguetown/clothing/onmob/shirts.dmi
  icons/roguetown/clothing/pants.dmi
  icons/roguetown/clothing/shirts.dmi
  icons/roguetown/weapons/32.dmi
  sound/music/combat_delf.ogg
  stonekeep.dme
Labels: Icons, New features

#741 Totod Order Emissary from Crusader transformation and Count/Countess honorary
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/rare/grenzelhoft.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/rare/zybantine.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/special/crusader.dm
Labels: Scheduled for testmerge

#498 Family Subsystem[GOOD FOR TESTMERGE!]
  code/__DEFINES/roguetown.dm
  code/controllers/subsystem/familytree.dm
  code/datums/dna.dm
  code/datums/heritage.dm
  code/datums/sexcon.dm
  code/game/objects/structures/fluff.dm
  code/modules/admin/admin_verbs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/jobs/job_types/roguetown/apprentices/prince.dm
  code/modules/jobs/job_types/roguetown/nobility/lady.dm
  code/modules/jobs/job_types/roguetown/nobility/lord.dm
  code/modules/jobs/job_types/roguetown/roguetown.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  icons/relations.dmi
  stonekeep.dme
Labels: Scheduled for testmerge, New features

#697 [Port] Breaking grabs gives resistence to them (0.8 seconds)
  code/modules/mob/living/living.dm
Labels: Scheduled for testmerge

#788 Familytree 1.1 species calc fixes
  code/controllers/subsystem/familytree.dm
  code/datums/heritage.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/examine.dm
Labels: Scheduled for testmerge

#795 Fixes Bows
  code/datums/mutable_appearance.dm
Labels: Scheduled for testmerge

#797 Drifter Spawn Brazier Fix (Bugfix, Mapping)
  _maps/map_files/roguetown/otherz/smallforest.dmm
Labels: Map, Bugfix

#806 Anthrax Mercenary Touch-Ups
  code/game/objects/items/rogueweapons/melee/knives.dm
  code/game/objects/items/rogueweapons/melee/swords.dm
  code/modules/jobs/job_types/roguetown/other/merc_classes/anthrax.dm
  icons/roguetown/weapons/32.dmi
Labels: Icons

#776 Autumn Cleaning part 2
  _maps/custom/roguehamlet.dmm
  _maps/custom/roguehamlet1.dmm
  _maps/custom/roguetown.dmm
  _maps/custom/stonekeep.dmm
  _maps/map_files/dakkatown/dakkatown.dmm
  _maps/map_files/dakkatown/otherz/dakkaforest.dmm
  _maps/map_files/dun_manor/dun_manor.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/map_files/old_maps/roguetown2.dmm
  _maps/map_files/old_maps/roguetown3.dmm
  _maps/map_files/roguetown/otherz/roguehamlet.dmm
  _maps/map_files/roguetown/roguetown.dmm
  _maps/map_files/rogueworld/roguetown.dmm
  _maps/roguehamlet/roguehamlet.dmm
  code/_globalvars/lists/maintenance_loot.dm
  code/game/objects/items/rogueitems/natural/flower.dm
  code/game/objects/items/storage/belt.dm
  code/modules/cargo/bounties/assistant.dm
  code/modules/cargo/packs.dm
  code/modules/cargo/packsrogue/food.dm
  code/modules/hydroponics/grown.dm
  code/modules/hydroponics/grown/ambrosia.dm
  code/modules/hydroponics/grown/cereals.dm
  code/modules/hydroponics/grown/citrus.dm
  code/modules/hydroponics/grown/cotton.dm
  code/modules/hydroponics/grown/flowers.dm
  code/modules/hydroponics/grown/misc.dm
  code/modules/hydroponics/grown/roguesmoke.dm
  code/modules/hydroponics/grown/roguetown.dm
  code/modules/hydroponics/grown/towercap.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/mining/abandoned_crates.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  modular/Neu_Farming/code/crafting_recipes.dm
  modular/Neu_Farming/code/produce.dm
  modular/Neu_Farming/code/seeds.dm
  stonekeep.dme
Labels: Scheduled for testmerge, Map

#809 The Levy Finally Arrives (Content, Balance)
  _maps/map_files/dun_manor/dun_manor.dmm
  code/__DEFINES/roguetown.dm
  code/modules/jobs/job_types/roguetown/garrison/garrisonarcher.dm
  code/modules/jobs/job_types/roguetown/garrison/garrisonguard.dm
Labels: Scheduled for testmerge, Map, New features

#818 Blood Homunculus hotfix
  code/game/objects/items/rogueweapons/intents.dm
  code/modules/mob/living/simple_animal/rogue/creacher/zizoid.dm
Labels: Bugfix

#747 Dwarf trait Poison Resistance & Poison fixes/tweaks
  code/__DEFINES/mobs.dm
  code/game/objects/items/rogueweapons/ranged/ammo.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/dwarf/dwarfm.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/roguetown/roguecrafting/items.dm
  code/modules/roguetown/roguejobs/alchemist/container.dm
  code/modules/roguetown/roguejobs/alchemist/reagents.dm
  modular/Neu_Farming/code/produce.dm
  modular/Neu_Food/code/NeuFood.dm
Labels: New features

#739 Belting_Merc_Mains_actually_satchel4
  code/modules/clothing/rogueclothes/storage.dm
  code/modules/jobs/job_types/roguetown/other/merc_classes/blackoak.dm
  code/modules/jobs/job_types/roguetown/other/merc_classes/boltslinger.dm
  code/modules/jobs/job_types/roguetown/other/merc_classes/grenzelhoft.dm
  code/modules/jobs/job_types/roguetown/other/merc_classes/steppesman.dm
  code/modules/jobs/job_types/roguetown/other/merc_classes/underdweller.dm
  code/modules/jobs/job_types/roguetown/other/merc_classes/zybantine.dm
  code/modules/roguetown/roguemachine/stockpile.dm
  code/modules/roguetown/roguemachine/submission.dm
Labels: Scheduled for testmerge

#815 Bard and Net hotfixes
  code/game/objects/items/rogueweapons/ranged/bows.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/bard.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  modular/Barding/code/Barding_instruments.dm
Labels: Bugfix

#805 DYESTATION, also lowers the sewing level of dresses. NO CONFLICTS NOW
  code/game/objects/structures/dystation.dm
  code/modules/roguetown/roguecrafting/sewing.dm
  code/modules/roguetown/roguecrafting/structure.dm
  icons/roguetown/misc/structure.dmi
  stonekeep.dme
Labels: Scheduled for testmerge

#821 Makes Totod Emissary a combat class
  code/modules/jobs/job_types/roguetown/adventurer/types/special/crusader.dm
Labels: Scheduled for testmerge

#792 Hats file finish
  code/__DEFINES/roguetown.dm
  code/modules/clothing/rogueclothes/hats.dm
Labels: Scheduled for testmerge

#824 Minifix Dunmanor
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Map, Bugfix

#823 Cleaning Update
  _maps/RandomZLevels/Academy.dmm
  _maps/RandomZLevels/SnowCabin.dmm
  _maps/RandomZLevels/caves.dmm
  _maps/RandomZLevels/moonoutpost19.dmm
  _maps/RandomZLevels/snowdin.dmm
  _maps/RandomZLevels/wildwest.dmm
  _maps/custom/roguehamlet.dmm
  _maps/custom/roguehamlet1.dmm
  _maps/custom/roguetown.dmm
  _maps/custom/stonekeep.dmm
  _maps/map_files/dakkatown/dakkatown.dmm
  _maps/map_files/dakkatown/otherz/dakkaswamp.dmm
  _maps/map_files/dun_manor/dun_manor.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/map_files/old_maps/roguetown2.dmm
  _maps/map_files/old_maps/roguetown3.dmm
  _maps/map_files/old_maps/roguetown4.dmm
  _maps/map_files/old_maps/roguetown5.dmm
  _maps/map_files/roguetown/otherz/roguehamlet.dmm
  _maps/map_files/roguetown/roguetown.dmm
  _maps/map_files/rogueworld/roguetown.dmm
  _maps/map_files/templates/lil_bog_shack/bog_shack_small_2.dmm
  _maps/map_files/templates/sk_dungeon/small_bog_dungeon_3.dmm
  _maps/map_files/templates/sk_dungeon/small_bog_dungeon_4.dmm
  _maps/roguehamlet/roguehamlet.dmm
  _maps/shuttles/whiteship_cere.dmm
  _maps/shuttles/whiteship_delta.dmm
  _maps/shuttles/whiteship_kilo.dmm
  _maps/templates/hilbertshotellore.dmm
  code/game/objects/effects/decals/cleanable/misc.dm
  code/game/objects/effects/spawners/bundle.dm
  code/game/objects/items/rogueitems/broom.dm
  code/game/objects/items/rogueitems/natural/clothfibersthorn.dm
  code/game/objects/items/weaponry.dm
  code/modules/roguetown/roguecrafting/items.dm
  code/modules/vending/autodrobe.dm
  stonekeep.dme
Labels: Map, New features

#794 95%test
  code/datums/components/crafting/crafting.dm
  code/modules/mob/living/roguetownprocs.dm
Labels: Scheduled for testmerge

#826 Mail fix & Changes
  code/modules/jobs/job_types/roguetown/church/adept.dm
  code/modules/jobs/job_types/roguetown/garrison/garrisonguard.dm
  code/modules/roguetown/roguemachine/mail.dm
Labels: Bugfix
