Repository Darkrp-community/OpenKeep, pull requests merged in 2024-10, with the labels that each got.

#513 Sets Humen, Half-Elf and Tiefling men to use the "Medium" bodytype, instead of their "Tall".
  code/modules/mob/living/carbon/human/species_types/roguetown/human/humen.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/other/halfelf.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/other/tiefling.dm
  icons/roguetown/mob/bodies/m/mm.dmi
Labels: Scheduled for testmerge, Squash me, Icons

#790 Niteman tweaks (mostly toward Nightmatrons)
  code/__DEFINES/jobs.dm
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/jobs/job_types/roguetown/nobility/nightman.dm
  icons/roguetown/clothing/onmob/armor.dmi
Labels: Merge conflict, Icons

#830 Fixes bad pathing on bucket on cargo pack for Goldface
  code/modules/cargo/packsrogue/tools.dm
Labels: Bugfix

#843 Papers, Please Update: New Gatehouses
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Map

#785 Butchering Update
  code/__DEFINES/roguetown.dm
  code/datums/components/crafting/recipes.dm
  code/game/objects/effects/decals/remains.dm
  code/game/objects/items/rogueitems/natural/animals.dm
  code/game/objects/items/rogueweapons/intents.dm
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/simple_animal/rogue/creacher/bigrat.dm
  code/modules/mob/living/simple_animal/rogue/creacher/bogbug.dm
  code/modules/mob/living/simple_animal/rogue/creacher/honeyspider.dm
  code/modules/mob/living/simple_animal/rogue/creacher/mole.dm
  code/modules/mob/living/simple_animal/rogue/creacher/shade.dm
  code/modules/mob/living/simple_animal/rogue/creacher/troll.dm
  code/modules/mob/living/simple_animal/rogue/creacher/trollbog.dm
  code/modules/mob/living/simple_animal/rogue/creacher/volf.dm
  code/modules/mob/living/simple_animal/rogue/creacher/zizoid.dm
  code/modules/mob/living/simple_animal/rogue/farm/chicken.dm
  code/modules/mob/living/simple_animal/rogue/farm/cow.dm
  code/modules/mob/living/simple_animal/rogue/farm/goat.dm
  code/modules/mob/living/simple_animal/rogue/game/saiga.dm
  code/modules/mob/living/simple_animal/rogue/rogueanimals.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/roguetown/roguecrafting/leather.dm
  code/modules/roguetown/roguecrafting/sewing.dm
  code/modules/roguetown/roguecrafting/weaving.dm
  icons/roguetown/items/natural.dmi
  modular/Creechers/code/trufflepig.dm
  modular/Creechers/icons/piggie.dmi
  modular/Neu_Food/code/cooked/NeuFood_snacks.dm
  modular/Neu_Food/code/raw/NeuFood_meat.dm
  modular/Neu_Food/code/raw/NeuFood_processed.dm
Labels: Scheduled for testmerge

#831 Raytown Adjustments: I've Procrastinated Long Enough
  _maps/map_files/roguetown/roguetown.dmm
Labels: Map

#856 Newlyweds Fix
  code/controllers/subsystem/familytree.dm
Labels: Bugfix

#848 Maybe Fix Dodge (Bugfix)
  code/modules/mob/living/roguetownprocs.dm
Labels: Scheduled for testmerge, Bugfix

#853 Make unbuying your own triumph conditions free
  code/controllers/subsystem/rogue/triumphs/triumphs.dm
Labels: Bugfix

#860 Tiefling Tails
  code/__DEFINES/mobs.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/other/tiefling.dm
  icons/roguetown/mob/bodies/attachments.dmi
Labels: Icons

#878 Fix BYOND members getting fewer slots
  code/modules/client/preferences.dm
Labels: Bugfix

#866 Deadites Revamp
  code/game/objects/items/rogueitems/bags.dm
  code/game/objects/items/rogueitems/natural/stones.dm
  code/game/objects/items/rogueweapons/intents.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/roguewindow.dm
  code/modules/antagonists/roguetown/villain/zomble.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/life.dm
  icons/mob/roguehud.dmi
  icons/program_icons/alarm_green.gif
  icons/program_icons/alarm_red.gif
  icons/program_icons/batt_100.gif
  icons/program_icons/batt_20.gif
  icons/program_icons/batt_40.gif
  icons/program_icons/batt_5.gif
  icons/program_icons/batt_60.gif
  icons/program_icons/batt_80.gif
  icons/program_icons/charging.gif
  icons/program_icons/downloader_finished.gif
  icons/program_icons/downloader_running.gif
  icons/program_icons/ntnrc_idle.gif
  icons/program_icons/ntnrc_new.gif
  icons/program_icons/power_norm.gif
  icons/program_icons/power_warn.gif
  icons/program_icons/sig_high.gif
  icons/program_icons/sig_lan.gif
  icons/program_icons/sig_low.gif
  icons/program_icons/sig_none.gif
  icons/program_icons/smmon_0.gif
  icons/program_icons/smmon_1.gif
  icons/program_icons/smmon_2.gif
  icons/program_icons/smmon_3.gif
  icons/program_icons/smmon_4.gif
  icons/program_icons/smmon_5.gif
  icons/program_icons/smmon_6.gif
  icons/roguetown/mob/rotten.dmi
  sound/combat/hits/onglass/destroyfurniture.ogg
  sound/combat/hits/onglass/destroywalldoor.ogg
  sound/combat/hits/onglass/glassbreak (1).ogg
  sound/combat/hits/onglass/glassbreak (2).ogg
  sound/combat/hits/onglass/glassbreak (3).ogg
  sound/combat/hits/onglass/glasshit.ogg
  sound/combat/hits/onwood/destroyfurniture.ogg
  sound/combat/hits/onwood/destroywalldoor.ogg
  sound/combat/hits/onwood/education1.ogg
  sound/combat/hits/onwood/education2.ogg
  sound/combat/hits/onwood/education3.ogg
  sound/combat/hits/onwood/fence_hit1.ogg
  sound/combat/hits/onwood/fence_hit2.ogg
  sound/combat/hits/onwood/fence_hit3.ogg
Labels: Scheduled for testmerge, Bugfix

#886 Fix Missing Underworld Tolls (Bugfix)
  code/game/objects/effects/landmarks.dm
Labels: Bugfix

#872 TGM test
  _maps/map_files/roguetown/otherz/smallforest.dmm
Labels: Map, Bugfix

#849 Poison tweaks
  code/modules/roguetown/roguejobs/alchemist/reagents.dm
Labels: Scheduled for testmerge, Bugfix

#869 Wound Pain Tweaks
  code/datums/wounds/arteries.dm
  code/datums/wounds/bites.dm
  code/datums/wounds/fractures.dm
  code/datums/wounds/punctures.dm
  code/datums/wounds/slashes.dm
  code/datums/wounds/special.dm
Labels: Scheduled for testmerge, Bugfix

#870 Changes the Grab CD (0.8 -> 1.5)
  code/modules/mob/living/living.dm
Labels: Scheduled for testmerge

#888 Fixes New Recipes (Bugfix)
  code/modules/roguetown/roguecrafting/items.dm
Labels: Bugfix

#852 Map Changes: Moves Veteran's House and Adds in Rockhill Lake
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Map

#877 Udderly insane + Dying for a bin
  code/game/objects/structures/dystation.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/gutlunch.dm
  code/modules/mob/living/simple_animal/rogue/farm/cow.dm
  code/modules/mob/living/simple_animal/rogue/farm/goat.dm
  code/modules/mob/living/simple_animal/rogue/farm/trufflepig.dm
  code/modules/mob/living/simple_animal/rogue/rogueanimals.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  icons/roguetown/items/food.dmi
  icons/roguetown/items/natural.dmi
  icons/roguetown/items/produce.dmi
  icons/roguetown/misc/structure.dmi
  icons/roguetown/mob/monster/piggie.dmi
  icons/roguetown/mob/trufflesniff.dmi
  modular/Creechers/icons/piggie.dmi
  modular/Creechers/sound/pighangry.ogg
  modular/Neu_Farming/icons/produce.dmi
  modular/Neu_Food/code/cooked/NeuFood_pies.dm
  modular/Neu_Food/code/raw/NeuFood_dough.dm
  modular/Neu_Food/code/raw/NeuFood_processed.dm
  sound/vo/mobs/cow/milking (1).ogg
  sound/vo/mobs/cow/milking (2).ogg
  sound/vo/mobs/pig/grunt (1).ogg
  sound/vo/mobs/pig/grunt (2).ogg
  sound/vo/mobs/pig/hangry.ogg
  stonekeep.dme
Labels: Scheduled for testmerge, Bugfix

#879 Bug fix about ore and cleaning floor tweaks
  code/game/objects/items/rogueitems/natural/clothfibersthorn.dm
  code/modules/roguetown/roguejobs/blacksmith/smelter.dm
Labels: Bugfix

#899 New Steward and Inn Peddlers
  _maps/map_files/dun_manor/dun_manor.dmm
  code/game/objects/items/rogueitems/keys.dm
  code/modules/roguetown/roguemachine/vendor.dm
Labels: Scheduled for testmerge

#901 Latejoin Family UI
  code/datums/heritage.dm
Labels: Scheduled for testmerge

#904 Veteran and Mayor Keyring Changes
  _maps/map_files/dun_manor/dun_manor.dmm
  code/game/objects/items/rogueitems/keyrings.dm
  code/game/objects/items/rogueitems/keys.dm
  code/modules/jobs/job_types/roguetown/garrison/veteran.dm
Labels: Map

#902 Restores the NeuFarm toolset
  code/modules/roguetown/roguejobs/gravedigger/tools.dm
  modular/Neu_Farming/code/plough.dm
  modular/Neu_Farming/code/tools.dm
  modular/Neu_Farming/icons/plough_big.dmi
Labels: Scheduled for testmerge

#876 Cabbits: The most foul, cruel and bad tempered feline rodent you ever set eyes on
  _maps/custom/roguehamlet.dmm
  _maps/map_files/dakkatown/dakkatown.dmm
  _maps/map_files/dun_manor/dun_manor.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/map_files/roguetown/roguetown.dmm
  _maps/roguehamlet/roguehamlet.dmm
  code/game/objects/items/rogueitems/bait.dm
  code/game/objects/items/rogueitems/natural/animals.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/rogue/creacher/troll.dm
  icons/roguetown/mob/cabbit.dmi
  sound/vo/mobs/rabbit/rabbit_alert.ogg
  sound/vo/mobs/rabbit/rabbit_death.ogg
  sound/vo/mobs/rabbit/rabbit_pain1.ogg
  sound/vo/mobs/rabbit/rabbit_pain2.ogg
Labels: Scheduled for testmerge, Map, Icons, New features

#850 Inhumen Pantheon Edits and New Demonic Patrons
  code/datums/gods/patrons/inhumen_pantheon.dm
Labels: Merge conflict

#928 [MAP] Merchant QOL Changes + Minor Fixes
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Scheduled for testmerge

#881 Official titles for Change Position
  code/modules/jobs/job_types/roguetown/nobility/titles.dm
  code/modules/jobs/jobs.dm
  stonekeep.dme
  strings/rt/Lore_Primer.json
  strings/rt/Lore_Primer.txt
Labels: Scheduled for testmerge

#926 Fixes Legendary Peasant Missing Gambeson (Bugfix)
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/rare/Lpeasant.dm
Labels: Bugfix

#918 Blunt Knockdown Fix
  code/modules/mob/living/carbon/human/species.dm
Labels: Scheduled for testmerge

#903 New Bushes
  _maps/custom/roguehamlet.dmm
  _maps/custom/roguehamlet1.dmm
  _maps/custom/roguetown.dmm
  _maps/custom/stonekeep.dmm
  _maps/map_files/dakkatown/dakkatown.dmm
  _maps/map_files/dun_manor/dun_manor.dmm
  _maps/map_files/old_maps/roguetown2.dmm
  _maps/map_files/old_maps/roguetown3.dmm
  _maps/map_files/old_maps/roguetown4.dmm
  _maps/map_files/old_maps/roguetown5.dmm
  _maps/map_files/roguetown/otherz/roguehamlet.dmm
  _maps/map_files/roguetown/roguetown.dmm
  _maps/map_files/roguewar/roguewar.dmm
  _maps/map_files/rogueworld/roguetown.dmm
  _maps/map_files/templates/lil_bog_shack/bog_shack_small_1.dmm
  _maps/map_files/templates/lil_bog_shack/bog_shack_small_2.dmm
  _maps/map_files/templates/lil_bog_shack/bog_shack_small_3.dmm
  _maps/roguehamlet/roguehamlet.dmm
  code/__DEFINES/span.dm
  code/game/area/roguetownareas.dm
  code/game/objects/effects/spawners/roguemapgen.dm
  code/game/objects/structures/roguetown/rogueflora.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/roguetown/mapgen/bog.dm
  code/modules/roguetown/mapgen/dakkamg/dakkaforestmg.dm
  code/modules/roguetown/mapgen/dakkamg/dakkaswampmg.dm
  code/modules/roguetown/mapgen/dakkamg/dakkatownmg.dm
  code/modules/roguetown/mapgen/decap.dm
  code/modules/roguetown/mapgen/forest.dm
  code/modules/roguetown/mapgen/rogueoutdoors.dm
  icons/roguetown/items/natural.dmi
  icons/roguetown/misc/foliage.dmi
  interface/stylesheet.dm
  modular/Neu_Farming/code/produce.dm
  modular/Neu_Food/code/NeuFood.dm
Labels: Scheduled for testmerge

#893 Please
  code/_compile_options.dm
  code/game/objects/items/rogueweapons/ranged/ammo.dm
  code/game/objects/items/rogueweapons/ranged/blowgun.dm
  code/modules/roguetown/roguecrafting/items.dm
  icons/roguetown/weapons/32.dmi
  icons/roguetown/weapons/64.dmi
  icons/roguetown/weapons/ammo.dmi
  sound/combat/Ranged/blowgun_shot.ogg
  stonekeep.dme
Labels: Scheduled for testmerge

#937 Blood & Tox heal tweak and minifixes
  _maps/custom/roguehamlet.dmm
  _maps/custom/roguehamlet1.dmm
  _maps/map_files/roguetown/otherz/roguehamlet.dmm
  _maps/roguehamlet/roguehamlet.dmm
  code/datums/pollutant.dm
  code/game/area/roguetownareas.dm
  code/game/objects/items/rogueitems/keys.dm
  code/game/objects/items/rogueweapons/melee/blunt.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/roguewindow.dm
  code/modules/cargo/bounties/chef.dm
  code/modules/cargo/packs.dm
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/food_and_drinks/food/snacks/meat.dm
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/food_and_drinks/food/snacks_soup.dm
  code/modules/jobs/job_types/roguetown/other/mercenary.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/carbon/spirit/spirit.dm
  code/modules/mob/living/death.dm
  code/modules/mob/living/roguetownprocs.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/reagent_containers/bottle.dm
  code/modules/roguetown/roguejobs/alchemist/container.dm
  code/modules/roguetown/roguejobs/farmer/plantedcrops.dm
  code/modules/underworld/underworld.dm
  code/modules/vending/boozeomat.dm
  icons/obj/reagentfillings.dmi
  modular/Mapping/Mapping_aides.dm
  modular/Neu_Farming/code/fermenting_barrel.dm
  modular/Neu_Farming/code/plant_def.dm
  modular/Neu_Farming/code/produce.dm
  modular/Neu_Farming/code/soil.dm
  modular/Neu_Food/code/NeuFood.dm
  modular/Neu_Food/code/raw/NeuFood_veggies.dm
Labels: Scheduled for testmerge, Bugfix

#946 Swaps the Steward and the Garrison Buildings + Adds Royal Stable
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Scheduled for testmerge, Map

#890 Underworld Edit
  _maps/map_files/generic/CentCom.dmm
  _maps/map_files/roguetown/otherz/underworld.dmm
Labels: Scheduled for testmerge, Map, Bugfix

#938 Bow Rework
  code/game/objects/items/rogueweapons/ranged/ammo.dm
  code/game/objects/items/rogueweapons/ranged/bows.dm
  code/game/objects/items/rogueweapons/ranged/crossbows.dm
  code/modules/projectiles/guns/ballistic.dm
  icons/roguetown/weapons/ammo.dmi
  icons/roguetown/weapons/bows.dmi
Labels: Scheduled for testmerge

#950 Removes drifters way better than the last PR
  code/controllers/subsystem/rogue/role_class_handler/drifter_queue/drifter_queue.dm
  code/modules/jobs/job_types/roguetown/adventurer/adventurer.dm
  code/modules/jobs/job_types/roguetown/adventurer/pilgrim.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/_advclass.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/assassin.dm
  code/modules/jobs/jobs.dm
Labels: Scheduled for testmerge

#956 Fixes Missing Housekeeper Boots (Bugfix)
  code/modules/jobs/job_types/roguetown/peasants/butler.dm
Labels: Bugfix

#939 New Sewing Recipes
  code/modules/roguetown/roguecrafting/sewing.dm
Labels: Scheduled for testmerge

#873 Adds a small southern dungeon section to the Raytown sewers, as well as a small mine in the Village
  _maps/map_files/roguetown/roguetown.dmm
Labels: Map

#964 Wall Key Fixes + Keyring Cleanup + Minor Spawn Changes
  _maps/map_files/dun_manor/dun_manor.dmm
  code/game/objects/items/rogueitems/keyrings.dm
  code/modules/jobs/job_types/roguetown/apprentices/squire.dm
  code/modules/jobs/job_types/roguetown/garrison/royalguard.dm
  code/modules/jobs/job_types/roguetown/peasants/grabber.dm
Labels: Scheduled for testmerge

#975 Fixes Small Thrones (Bugfix)
  _maps/custom/roguetown.dmm
  _maps/custom/stonekeep.dmm
  _maps/map_files/dakkatown/dakkatown.dmm
  _maps/map_files/dun_manor/dun_manor.dmm
  _maps/map_files/old_maps/roguetown2.dmm
  _maps/map_files/old_maps/roguetown4.dmm
  _maps/map_files/old_maps/roguetown5.dmm
  _maps/map_files/roguetown/roguetown.dmm
  _maps/map_files/rogueworld/roguetown.dmm
  code/game/objects/structures/beds_chairs/roguechair.dm
Labels: Bugfix

#908 Revival Sickness
  code/datums/status_effects/rogue/debuff.dm
  code/modules/spells/roguetown/acolyte/astrata.dm
Labels: Scheduled for testmerge

#978 The Fancyhat Fix
  _maps/map_files/generic/CentCom.dmm
  code/__DEFINES/roguetown.dm
  code/datums/status_effects/rogue/roguebuff.dm
  code/datums/stress/positive_events.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/storage.dm
  code/modules/jobs/job_types/roguetown/adventurer/DRIFTERZ.dm
  code/modules/jobs/job_types/roguetown/adventurer/adventurer.dm
  code/modules/jobs/job_types/roguetown/adventurer/pilgrim.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/barbarian.dm
  code/modules/jobs/job_types/roguetown/adventurer/villager.dm
  code/modules/jobs/job_types/roguetown/apprentices/bapprentice.dm
  code/modules/jobs/job_types/roguetown/peasants/bathmaid.dm
  code/modules/jobs/job_types/roguetown/serfs/blacksmith.dm
  code/modules/jobs/job_types/roguetown/serfs/tailor.dm
  icons/roguetown/clothing/onmob/head.dmi
  sound/items/soaping.ogg
Labels: Bugfix

#941 Aunts and In Laws Family System Expansion
  code/__DEFINES/roguetown.dm
  code/controllers/subsystem/familytree.dm
  code/datums/heritage.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
Labels: Scheduled for testmerge

#942 Mount Decapitation Overhaul (You should FEAR the mountain)
  _maps/map_files/roguetown/otherz/smalldecap.dmm
Labels: Scheduled for testmerge, Map

#983 Towner Housing Changes + Keep Guest Housing + Road Changes + Spawn Changes
  _maps/map_files/dun_manor/dun_manor.dmm
  code/modules/roguetown/roguemachine/vendor.dm
Labels: Map

#993 Job Bans for RT
  code/modules/admin/sql_ban_system.dm
  html/admin/banpanel.css
Labels: Scheduled for testmerge

#972 Vampire Lord bugfix and runtime squashing
  code/modules/antagonists/roguetown/villain/vampirelord.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/status_procs.dm
  code/modules/mob/living/carbon/life.dm
  code/rt.dm
Labels: Scheduled for testmerge, Squash me, Bugfix, New features

#998 The Dodgening
  code/modules/mob/living/roguetownprocs.dm
  code/modules/mob/mob_movement.dm
Labels: Scheduled for testmerge

#947 You can no longer sleep in armor
  code/__DEFINES/obj_flags.dm
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/feet.dm
  code/modules/clothing/rogueclothes/gloves.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/mask.dm
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/clothing/rogueclothes/pants.dm
  code/modules/mob/living/carbon/life.dm
Labels: Scheduled for testmerge

#962 Treasury payment/fines fix (hopefully)
  code/controllers/subsystem/rogue/treasury.dm
Labels: Scheduled for testmerge

#859 zizo cult ritual additions, rebalances and such
  code/game/gamemodes/roguetown/roguetown.dm
  code/modules/antagonists/roguetown/villain/zizocult.dm
  code/modules/clothing/rogueclothes/cloaks.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/mob/living/simple_animal/rogue/creacher/zizoid.dm
Labels: Scheduled for testmerge

#1004 Death of the Miner Worm
  code/_onclick/item_attack.dm
  code/game/objects/items/rogueweapons/ranged/blowgun.dm
  code/game/objects/items/rogueweapons/ranged/bows.dm
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/clothing/rogueclothes/storage.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/amazon.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/qatil.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/rare/zybantine.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/special/crusader.dm
  code/modules/jobs/job_types/roguetown/other/merc_classes/zybantine.dm
  code/modules/jobs/job_types/roguetown/other/mercenary.dm
  icons/roguetown/mob/facial.dmi
  icons/roguetown/weapons/ammo.dmi
  icons/roguetown/weapons/bows.dmi
Labels: Scheduled for testmerge

#987 Miracle Tweak
  code/controllers/subsystem/rogue/devotion.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/blacksmith.dm
  code/modules/spells/roguetown/acolyte/general.dm
  code/modules/spells/spell.dm
Labels: Scheduled for testmerge

#1009 This PR probably fixes the sunlight issue, better than reverting the entire PR
  code/modules/procedural_mapping/mapGeneratorModule.dm
Labels: Scheduled for testmerge

#1006 System for beds, Fog lore book added, adventurer paladin dupefix
  _maps/custom/roguehamlet.dmm
  _maps/custom/roguehamlet1.dmm
  _maps/custom/roguetown.dmm
  _maps/custom/stonekeep.dmm
  _maps/map_files/dakkatown/dakkatown.dmm
  _maps/map_files/dakkatown/otherz/dakkaswamp.dmm
  _maps/map_files/dun_manor/dun_manor.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/map_files/old_maps/roguetown2.dmm
  _maps/map_files/old_maps/roguetown4.dmm
  _maps/map_files/old_maps/roguetown5.dmm
  _maps/map_files/roguetown/otherz/roguehamlet.dmm
  _maps/map_files/roguetown/otherz/smalldecap.dmm
  _maps/map_files/roguetown/otherz/smallforest.dmm
  _maps/map_files/roguetown/roguetown.dmm
  _maps/map_files/rogueworld/roguetown.dmm
  _maps/map_files/templates/sk_dungeon/small_bog_dungeon_1.dmm
  _maps/roguehamlet/roguehamlet.dmm
  code/datums/weather/weather_types/roguetown/fog.dm
  code/game/objects/items/rogueitems/books.dm
  code/game/objects/structures/beds_chairs/roguechair.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/donator/paladin.dm
  stonekeep.dme
  strings/books/tales15.json
Labels: Scheduled for testmerge, Map

#1015 Lamias and Headless Appear in Rockhill [Good for Testmerge]
  code/modules/mob/living/simple_animal/rogue/creacher/headless.dm
  code/modules/mob/living/simple_animal/rogue/creacher/lamia.dm
  stonekeep.dme
Labels: Scheduled for testmerge

#1007 Wound Tweaks 2: The Bloodening
  code/__DEFINES/mobs.dm
  code/datums/wounds/arteries.dm
  code/datums/wounds/bites.dm
  code/datums/wounds/fractures.dm
  code/datums/wounds/punctures.dm
  code/datums/wounds/slashes.dm
  code/datums/wounds/special.dm
  code/game/objects/items/rogueweapons/rogueweapon.dm
  code/modules/antagonists/roguetown/villain/vampire.dm
  code/modules/antagonists/roguetown/villain/vampirelord.dm
  code/modules/mob/living/blood.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/roguetown/roguejobs/alchemist/reagents.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
Labels: Scheduled for testmerge

#1023 Revert "Treasury payment/fines fix (hopefully)"
  code/controllers/subsystem/rogue/treasury.dm
Labels: Scheduled for testmerge

#1033 Dead people can hear thru deafness and beheading - port
  code/modules/mob/living/carbon/carbon_defense.dm
Labels: Bugfix

#839 The Magical Update (TM ready) ((I fixed it)) (((100% chance of success BABY!!!!)))
  code/__DEFINES/lighting.dm
  code/__DEFINES/traits.dm
  code/_onclick/hud/action_button.dm
  code/datums/mind.dm
  code/datums/status_effects/rogue/roguebuff.dm
  code/game/objects/items/granters.dm
  code/game/objects/items/rogueitems/magic.dm
  code/game/objects/items/rogueweapons/intents.dm
  code/game/objects/structures/crates_lockers/roguetown.dm
  code/game/objects/structures/roguewindow.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/sorceress.dm
  code/modules/jobs/job_types/roguetown/nobility/archivist.dm
  code/modules/jobs/job_types/roguetown/nobility/magician.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/living.dm
  code/modules/spells/roguetown/wizard.dm
  code/modules/spells/spell.dm
  code/modules/spells/spell_types/knock.dm
  icons/mob/actions/roguespells.dmi
  icons/mob/roguehudgrabs.dmi
  icons/roguetown/items/misc.dmi
  sound/foley/finger-snap.ogg
  sound/magic/blade_burst.ogg
  sound/magic/charging_fire.ogg
  sound/magic/charging_lightning.ogg
  sound/magic/haste.ogg
  sound/magic/repulse.ogg
Labels: Scheduled for testmerge

#1024 Dunmanor Mapgen updates & Ship
  _maps/map_files/dun_manor/dun_manor.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/map_files/roguetown/otherz/smallforest.dmm
  _maps/map_files/roguetown/otherz/underworld.dmm
  code/game/area/roguetownareas.dm
  code/game/objects/structures/beds_chairs/roguechair.dm
  code/game/turfs/closed/_closed.dm
  code/modules/roguetown/mapgen/forest.dm
  modular/Mapping/Mapping_aides.dm
Labels: Scheduled for testmerge

#1020 Lonely Priest Seeking Choir
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/robes.dm
  code/modules/events/rogue/_rogue.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/spells/roguetown/acolyte/astrata.dm
  icons/roguetown/clothing/head.dmi
  icons/roguetown/clothing/onmob/64x64/head.dmi
Labels: Scheduled for testmerge
