Repository Darkrp-community/OpenKeep, pull requests merged in 2024-06, with the labels that each got.

#90 Ports BLACKSTONE #956 'Area fixes + new area intro texts'
  code/game/area/areas.dm
  code/game/area/roguetownareas.dm
Labels: scheduled for testmerge

#89 Ports numerous checkdefence fixes from BLACKSTONE
  code/__DEFINES/traits.dm
  code/_onclick/item_attack.dm
  code/controllers/subsystem/ticker.dm
  code/datums/status_effects/rogue/debuff.dm
  code/datums/status_effects/rogue/roguebuff.dm
  code/game/objects/items/rogueweapons/intents.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/bard.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/ranger.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/assassin.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/sentinel.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rogue.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/roguetownprocs.dm
  code/modules/mob/mob_movement.dm
  code/modules/roguetown/roguecrafting/leather.dm
  code/modules/roguetown/roguecrafting/sewing.dm
Labels: scheduled for testmerge

#65 spriting upgrades
  icons/roguetown/weapons/32.dmi
  icons/roguetown/weapons/64.dmi
  icons/roguetown/weapons/tools.dmi
Labels: squash me

#138 Changes 'Bucket helm' to 'Great Helm'
  code/modules/clothing/rogueclothes/hats.dm
Labels: unapproved restricted changes

#141 Inn Expansion 2
  _maps/map_files/roguetown/roguetown.dmm
Labels: map

#177 fixes drow accent, changes/fixes word filter, removes slurs to comply with github ToS
  strings/accent_universal.json
  strings/french_replacement.json
Labels: scheduled for testmerge

#238 RingWorms
  code/__DEFINES/traits.dm
  code/datums/wounds/special.dm
  code/game/turfs/open/water.dm
  code/modules/clothing/rogueclothes/rings.dm
  code/modules/roguetown/roguejobs/fisher/leeches.dm
  code/modules/roguetown/roguejobs/fisher/worms.dm
  code/modules/roguetown/roguemachine/scomm.dm
  icons/roguetown/clothing/rings.dmi
  icons/roguetown/items/misc.dmi
  icons/roguetown/items/natural.dmi
  icons/roguetown/items/surgery.dmi
Labels: scheduled for testmerge

#239 QoL big PR
  code/__HELPERS/roundend.dm
  code/datums/components/rotting.dm
  code/game/area/areas.dm
  code/game/objects/items/clown_items.dm
  code/game/objects/items/rogueitems/books.dm
  code/game/objects/structures/fluff.dm
  code/modules/client/client_procs.dm
  code/modules/library/book.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/rogue.dm
  code/modules/roguetown/roguemachine/merchant.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  code/modules/surgery/organs/organ_internal.dm
  code/modules/surgery/organs/stomach.dm
Labels: scheduled for testmerge

#237 Gravedigger Nature Healing + Mason + Miner Update
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/miner.dm
  code/modules/jobs/job_types/roguetown/peasants/gravedigger.dm
  code/modules/jobs/job_types/roguetown/serfs/mason.dm
  code/modules/roguetown/roguejobs/gravedigger/tools.dm
  icons/roguetown/weapons/32.dmi
  icons/roguetown/weapons/64.dmi
  icons/roguetown/weapons/tools.dmi
Labels: unapproved restricted changes

#240 ports ghetto farming and also lets you actually gain farming skill
  code/modules/roguetown/roguejobs/farmer/chaff.dm
  code/modules/roguetown/roguejobs/farmer/plantedcrops.dm
Labels: scheduled for testmerge

#241 Temporary Map-Gen "Fix"
  _maps/map_files/roguetown/roguetown.dmm
  code/game/objects/effects/spawners/roguemapgen.dm
  code/game/objects/items/candle.dm
  icons/obj/structures_spawners.dmi
Labels: scheduled for testmerge

#247 De-Gentrifies Bandit Spawning (De-Driftering Bandits)
  code/__DEFINES/roguetown.dm
  code/game/gamemodes/roguetown/roguetown.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/bandit.dm
  stonekeep.dme
Labels: scheduled for testmerge

#144 Barracks Remodel
  _maps/map_files/roguetown/roguetown.dmm
Labels: map, unapproved restricted changes
