Repository Darkrp-community/OpenKeep, pull requests merged in 2024-11, with the labels that each got.

#1027 Misc Antag Fixes
  code/__DEFINES/role_preferences.dm
  code/datums/status_effects/rogue/debuff.dm
  code/game/gamemodes/clown_ops/bananium_bomb.dm
  code/game/gamemodes/clown_ops/clown_ops.dm
  code/game/gamemodes/clown_ops/clown_weapons.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/gamemodes/traitor/double_agents.dm
  code/game/objects/items/rogueweapons/melee/swords.dm
  code/modules/antagonists/_common/antag_spawner.dm
  code/modules/antagonists/changeling/powers/pheromone_receptors.dm
  code/modules/antagonists/nukeop/clownop.dm
  code/modules/antagonists/nukeop/equipment/nuclear_challenge.dm
  code/modules/antagonists/roguetown/villain/vampire.dm
  code/modules/antagonists/roguetown/villain/zomble.dm
  code/modules/antagonists/traitor/IAA/internal_affairs.dm
  code/modules/mining/abandoned_crates.dm
  code/modules/mob/living/simple_animal/rogue/creacher/troll.dm
  code/modules/mob/living/simple_animal/rogue/creacher/trollbog.dm
  code/modules/uplink/uplink_devices.dm
  code/modules/uplink/uplink_items.dm
  modular/Neu_Food/code/NeuFood.dm
  stonekeep.dme
Labels: Scheduled for testmerge, Bugfix

#1018 King's Rod Changes
  code/_globalvars/lists/objects.dm
  code/game/objects/items/rogueweapons/melee/special.dm
Labels: Scheduled for testmerge

#1049 Fixes an issue where the Captain could still be a Zizoid despite #1039's intended changes.
  code/modules/jobs/jobs.dm
Labels: Bugfix

#1038 Fixing hats
  _maps/map_files/dun_manor/dun_manor.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/map_files/roguetown/otherz/smallforest.dmm
  code/__DEFINES/traits.dm
  code/datums/status_effects/rogue/debuff.dm
  code/datums/stress/negative_events.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/rogueweapons/melee/axes.dm
  code/game/objects/structures/fluff.dm
  code/game/objects/structures/roguetown/rogueflora.dm
  code/game/objects/structures/traveltile.dm
  code/game/turfs/closed/wall/roguewalls.dm
  code/modules/antagonists/roguetown/villain/zomble.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/special/crusader.dm
  code/modules/jobs/job_types/roguetown/church/monk.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  code/modules/jobs/job_types/roguetown/other/skeleton.dm
  code/modules/mob/living/carbon/human/npc/goblin.dm
  code/modules/mob/living/carbon/human/npc/orc.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/elf/elfw.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/simple_animal/rogue/creacher/troll.dm
  code/modules/mob/living/simple_animal/rogue/creacher/trollbog.dm
  code/modules/mob/living/simple_animal/rogue/rogueanimals.dm
  code/modules/roguetown/mapgen/bog.dm
  code/modules/spells/roguetown/acolyte/dendor.dm
  code/modules/spells/roguetown/acolyte/eora.dm
  icons/roguetown/mob/monster/Trolls.dmi
  modular/Mapping/Mapping_aides.dm
Labels: Scheduled for testmerge

#1053 New Sprites From Azure Peak
  code/datums/components/footstep.dm
  code/game/objects/structures/dystation.dm
  code/game/turfs/open/floor/roguefloor.dm
  code/modules/clothing/rogueclothes/feet.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/clothing/shoes/_shoes.dm
  code/modules/roguetown/roguecrafting/leather.dm
  code/modules/roguetown/roguecrafting/sewing.dm
  icons/roguetown/clothing/feet.dmi
  icons/roguetown/clothing/head.dmi
  icons/roguetown/clothing/onmob/feet.dmi
  icons/roguetown/clothing/onmob/head.dmi
  icons/turf/roguefloor.dmi
Labels: Merge conflict

#1052 Comments melee embeds and nets/bola acquisition
  code/datums/wounds/arteries.dm
  code/game/objects/items/rogueweapons/rogueweapon.dm
  code/modules/cargo/packsrogue/weapons.dm
  code/modules/jobs/job_types/roguetown/other/merc_classes/anthrax.dm
  code/modules/roguetown/roguecrafting/items.dm
  code/modules/surgery/surgery_tools_rogue.dm
Labels: Scheduled for testmerge

#1012 Archivist & Library Update
  _maps/map_files/dun_manor/dun_manor.dmm
  _maps/map_files/generic/CentCom.dmm
  code/__DEFINES/say.dm
  code/controllers/subsystem/dbcore.dm
  code/game/objects/items/rogueitems/books.dm
  code/game/objects/items/rogueitems/keyrings.dm
  code/game/objects/items/rogueitems/keys.dm
  code/modules/cargo/packs.dm
  code/modules/clothing/rogueclothes/shirts.dm
  code/modules/jobs/job_types/roguetown/nobility/archivist.dm
  code/modules/language/codespeak.dm
  code/modules/library/lib_machines.dm
  code/modules/library/random_books.dm
  code/modules/paperwork/paper.dm
  code/modules/roguetown/roguecrafting/items.dm
  code/modules/roguetown/roguemachine/vendor.dm
  icons/roguetown/clothing/onmob/shirts.dmi
  icons/roguetown/clothing/shirts.dmi
  icons/roguetown/items/books.dmi
  icons/roguetown/misc/machines.dmi
  sound/misc/ppress.ogg
  stonekeep.dme
Labels: Scheduled for testmerge, Merge conflict

#1066 Hairfix
  _maps/map_files/dun_manor/dun_manor.dmm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/briar.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  icons/roguetown/mob/hair_extensions.dmi
Labels: Bugfix

#1067 Mail Directory (Just need to map in the names cause I'm bored to do it)
  code/modules/roguetown/roguemachine/mail.dm
Labels: Scheduled for testmerge

#1058 Armor system
  _maps/map_files/dun_manor/dun_manor.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/map_files/roguetest/roguetest.dmm
  code/__DEFINES/roguetown.dm
  code/modules/antagonists/roguetown/villain/bandit.dm
  code/modules/antagonists/roguetown/villain/vampirelord.dm
  code/modules/antagonists/roguetown/villain/zizocult.dm
  code/modules/cargo/packsrogue/armor.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/cloaks.dm
  code/modules/clothing/rogueclothes/feet.dm
  code/modules/clothing/rogueclothes/gloves.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/mask.dm
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/clothing/rogueclothes/npc/goblin.dm
  code/modules/clothing/rogueclothes/npc/orc.dm
  code/modules/clothing/rogueclothes/pants.dm
  code/modules/clothing/suits/toggles.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/heartfelthand.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/qatil.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/rare/grenzelhoft.dm
  code/modules/jobs/job_types/roguetown/church/adept.dm
  code/modules/jobs/job_types/roguetown/church/inquisitor.dm
  code/modules/jobs/job_types/roguetown/garrison/garrisonguard.dm
  code/modules/jobs/job_types/roguetown/other/merc_classes/grenzelhoft.dm
  code/modules/jobs/job_types/roguetown/other/merc_classes/steppesman.dm
  code/modules/mob/living/carbon/human/npc/zizombies.dm
  code/modules/mob/mob_movement.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/armor.dm
Labels: Scheduled for testmerge

#1054 Struck through the heart
  code/datums/status_effects/rogue/roguestatus.dm
  code/modules/mob/living/carbon/rogfatstam.dm
  code/modules/spells/roguetown/wizard.dm
Labels: Scheduled for testmerge, New features

#1080 Little Hotfix
  code/game/objects/items/rogueweapons/melee/knives.dm
  code/game/objects/items/rogueweapons/ranged/ammo.dm
  code/game/objects/structures/dystation.dm
  code/game/objects/structures/fireaxe.dm
  code/game/objects/structures/fluff.dm
  code/game/objects/structures/walldeco.dm
  code/game/turfs/open/floor/roguefloor.dm
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/pants.dm
  code/modules/food_and_drinks/food/snacks.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/qatil.dm
  code/modules/jobs/job_types/roguetown/other/merc_classes/zybantine.dm
  code/modules/mob/living/carbon/spirit/spirit.dm
  code/modules/roguetown/roguecrafting/alchemy/potionbuffs.dm
  icons/roguetown/misc/64x32.dmi
  icons/roguetown/misc/decoration.dmi
  icons/turf/floors/woodalt.dmi
  icons/turf/floors/woodalt_turned.dmi
  icons/turf/roguefloor.dmi
  modular/Mapping/Mapping_aides.dm
  modular/Mapping/icons/96x96.dmi
  modular/Mapping/icons/decoration.dmi
  modular/Neu_Food/code/NeuFood.dm
Labels: Scheduled for testmerge, Bugfix

#1057 Addresses some issues in delimb breakpoints, makes "easy dismemberable" mobs slightly more vulnerable to dismembering.
  code/game/objects/items/rogueweapons/rogueweapon.dm
Labels: Scheduled for testmerge

#1075 Beer gut providence
  _maps/map_files/dun_manor/dun_manor.dmm
  _maps/map_files/old_maps/roguetown2.dmm
  _maps/map_files/roguetown/roguetown.dmm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/rogueitems/keyrings.dm
  code/game/objects/items/rogueitems/keys.dm
  code/game/turfs/open/floor/roguefloor.dm
  code/modules/jobs/job_types/roguetown/serfs/innkeep.dm
  code/modules/roguetown/roguemachine/vendor.dm
  icons/roguetown/misc/64x32.dmi
  icons/turf/floors/bear.dmi
  icons/turf/floors/woodalt.dmi
  icons/turf/floors/woodalt_turned.dmi
  icons/turf/roguefloor.dmi
  modular/Mapping/Mapping_aides.dm
  modular/Mapping/icons/96x96.dmi
Labels: Scheduled for testmerge

#1081 Vampire: the Stakening
  code/datums/wounds/arteries.dm
  code/datums/wounds/bites.dm
  code/datums/wounds/slashes.dm
  code/datums/wounds/special.dm
  code/game/objects/items/rogueitems/natural/wood.dm
  code/game/objects/items/rogueweapons/melee/knives.dm
  code/game/objects/items/rogueweapons/melee/swords.dm
  code/game/objects/items/rogueweapons/melee/whips.dm
  code/modules/antagonists/roguetown/villain/vampire.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/witchhunter.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/grabbing.dm
  code/modules/mob/living/living_wounds.dm
  code/modules/spells/roguetown/acolyte/general.dm
  code/modules/spells/roguetown/acolyte/necra.dm
  code/modules/surgery/bodyparts/bodypart_wounds.dm
Labels: Scheduled for testmerge

#1100 Leather pantsu
  _maps/map_files/roguetown/roguetown.dmm
  code/__DEFINES/roguetown.dm
  code/game/objects/items/rogueweapons/melee/axes.dm
  code/game/objects/items/rogueweapons/melee/knives.dm
  code/game/objects/items/rogueweapons/rogueweapon.dm
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/pants.dm
  code/modules/jobs/job_types/roguetown/serfs/tailor.dm
  code/modules/roguetown/roguecrafting/leather.dm
  code/modules/roguetown/roguecrafting/sewing.dm
  code/modules/roguetown/roguecrafting/weaving.dm
Labels: Scheduled for testmerge

#1110 Some fixes
  _maps/map_files/dun_manor/dun_manor.dmm
  _maps/map_files/roguetown/roguetown.dmm
  code/datums/components/spawner.dm
  code/datums/gods/patrons/divine_pantheon.dm
  code/game/objects/items/rogueweapons/melee/blunt.dm
  code/game/objects/items/rogueweapons/melee/swords.dm
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/mob/living/carbon/human/npc/skeleton.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
  icons/roguetown/clothing/head.dmi
  icons/roguetown/weapons/custom.dmi
  modular/Mapping/Mapping_aides.dm
  modular/Neu_Farming/icons/plough.dmi
Labels: Bugfix

#1113 Update natural.dmi
  icons/roguetown/items/natural.dmi
Labels: Bugfix

#1112 Fixes devotion consumption
  code/controllers/subsystem/rogue/devotion.dm
  code/modules/spells/roguetown/_roguetown.dm
  code/modules/spells/roguetown/acolyte/astrata.dm
  code/modules/spells/roguetown/acolyte/dendor.dm
  code/modules/spells/roguetown/acolyte/eora.dm
  code/modules/spells/roguetown/acolyte/general.dm
  code/modules/spells/roguetown/acolyte/necra.dm
  code/modules/spells/roguetown/acolyte/noc.dm
  code/modules/spells/roguetown/acolyte/pestra.dm
  code/modules/spells/roguetown/confessor.dm
  code/modules/spells/roguetown/jester.dm
  code/modules/spells/roguetown/wizard.dm
  code/modules/spells/spell.dm
  code/modules/spells/spell_types/aimed.dm
  code/modules/spells/spell_types/wizard.dm
Labels: Scheduled for testmerge, Bugfix

#1102 New encounters
  _maps/map_files/roguetown/otherz/smalldecap.dmm
  _maps/map_files/roguetown/otherz/smalldecap.json
  code/game/area/roguetownareas.dm
Labels: Scheduled for testmerge

#1062 Magick PR 2 Electric Boogaloo
  code/__DEFINES/traits.dm
  code/_onclick/drag_drop.dm
  code/datums/status_effects/rogue/roguebuff.dm
  code/game/turfs/open/floor/roguefloor.dm
  code/modules/spells/roguetown/wizard.dm
  icons/mob/actions/roguespells.dmi
Labels: Scheduled for testmerge

#1069 Dodge/Parry Experimental Tweaking
  code/modules/mob/living/roguetownprocs.dm
Labels: Scheduled for testmerge

#1135 Couple clothes & mapclean
  _maps/map_files/templates/sk_dungeon/labyrinth_of_xylix.dmm
  _maps/templates/medium_shuttle1.dmm
  _maps/templates/medium_shuttle2.dmm
  _maps/templates/medium_shuttle3.dmm
  _maps/templates/medium_shuttle4.dmm
  _maps/templates/sk_dungeons.dm
  _maps/templates/small_asteroid_1.dmm
  _maps/templates/small_shuttle_1.dmm
  code/__DEFINES/colors.dm
  code/modules/clothing/rogueclothes/cloaks.dm
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/clothing/rogueclothes/pants.dm
  code/modules/jobs/job_types/roguetown/garrison/garrisonguard.dm
  code/modules/jobs/job_types/roguetown/garrison/veteran.dm
  code/modules/jobs/job_types/roguetown/other/skeleton.dm
  code/modules/roguetown/roguecrafting/weaving.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/armor.dm
  code/modules/roguetown/roguejobs/farmer/tools.dm
  icons/roguetown/clothing/cloaks.dmi
  icons/roguetown/clothing/onmob/cloaks.dmi
  icons/roguetown/clothing/onmob/head.dmi
  icons/roguetown/clothing/onmob/helpers/sleeves_pants.dmi
  icons/roguetown/clothing/onmob/pants.dmi
  icons/roguetown/clothing/pants.dmi
  modular/Neu_Farming/code/tools.dm
Labels: Bugfix

#1132 Armor/Weapon Post-Rework Second Pass
  code/__DEFINES/combat.dm
  code/__DEFINES/roguetown.dm
  code/game/objects/items/rogueweapons/intents.dm
  code/game/objects/items/rogueweapons/melee/axes.dm
  code/game/objects/items/rogueweapons/melee/blunt.dm
  code/game/objects/items/rogueweapons/melee/knives.dm
  code/game/objects/items/rogueweapons/melee/polearms.dm
  code/game/objects/items/rogueweapons/melee/swords.dm
  code/game/objects/items/rogueweapons/rogueweapon.dm
  code/game/objects/items/rogueweapons/shields.dm
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/feet.dm
  code/modules/clothing/rogueclothes/gloves.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/mask.dm
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/clothing/rogueclothes/pants.dm
  code/modules/clothing/rogueclothes/shirts.dm
  code/modules/clothing/rogueclothes/wrists.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
Labels: Scheduled for testmerge

#1143 Fix for the alto thing
  _maps/map_files/roguetown/roguetown.dmm
  code/game/objects/items/rogueweapons/melee/blunt.dm
  icons/roguetown/weapons/custom.dmi
  icons/roguetown/weapons/custom_64.dmi
  icons/roguetown/weapons/shillelagh.dmi
Labels: Bugfix

#1125 Moves Necran Acolyte to Gravedigger
  _maps/map_files/dakkatown/dakkatown.dmm
  _maps/map_files/dun_manor/dun_manor.dmm
  code/__DEFINES/jobs.dm
  code/__DEFINES/roguetown.dm
  code/datums/gods/patrons/divine_pantheon.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/rogueitems/keyrings.dm
  code/modules/antagonists/roguetown/villain/vampirelord.dm
  code/modules/jobs/job_types/roguetown/church/monk.dm
  code/modules/jobs/job_types/roguetown/peasants/gravedigger.dm
  code/modules/jobs/jobs.dm
  code/modules/roguetown/roguejobs/gravedigger/tools.dm
  code/modules/spells/roguetown/acolyte/necra.dm
Labels: Scheduled for testmerge

#1129 No Ruler Required to Start the Round + Hand Can Be Ruler
  code/__HELPERS/roundend.dm
  code/controllers/subsystem/ticker.dm
  code/game/gamemodes/roguetown/roguetown.dm
  code/game/objects/items/rogueweapons/melee/special.dm
  code/modules/events/rogue/_rogue.dm
  code/modules/jobs/job_types/roguetown/nobility/hand.dm
  code/modules/roguetown/roguemachine/scomm.dm
Labels: Merge conflict

#1146 Fixes
  _maps/map_files/dun_manor/dun_manor.dmm
  _maps/shuttles/cargo_rogue.dmm
  code/modules/roguetown/roguejobs/farmer/tools.dm
  icons/roguetown/clothing/onmob/armor.dmi
  modular/Neu_Farming/code/tools.dm
Labels: Bugfix

#1156 Assorted Dun Manor Map Tweaks
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Scheduled for testmerge

#1155 Barding and Door update
  code/datums/status_effects/rogue/debuff.dm
  code/datums/stress/positive_events.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/lighting/roguelighting.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/window.dm
  code/modules/roguetown/roguemachine/drugmachine.dm
  icons/effects/music-note.dmi
  icons/roguetown/misc/pigflora.dmi
  modular/Barding/code/Barding_instruments.dm
  modular/Barding/code/music_effect.dm
  stonekeep.dme
Labels: Scheduled for testmerge

#1161 Masterkeeeey
  code/_onclick/item_attack.dm
  code/_onclick/other_mobs.dm
  code/game/objects/items/rogueitems/keys.dm
Labels: Scheduled for testmerge

#1166 Sound port
  code/__DEFINES/subsystems.dm
  code/_compile_options.dm
  code/controllers/subsystem/sounds.dm
  code/datums/looping_sounds/_looping_sound.dm
  code/datums/looping_sounds/item_sounds.dm
  code/datums/particle_weathers/_base.dm
  code/datums/weather/weather_types/ash_storm.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/devices/geiger_counter.dm
  code/game/objects/items/devices/reverse_bear_trap.dm
  code/game/objects/items/rogueitems/dmusicbox.dm
  code/game/objects/items/rogueweapons/intents.dm
  code/game/objects/lighting/roguelighting.dm
  code/game/objects/structures/fluff.dm
  code/game/objects/structures/roguetown/musicbox.dm
  code/game/objects/structures/roguetown/rogueflora.dm
  code/game/objects/structures/shower.dm
  code/game/sound.dm
  code/modules/mob/living/carbon/human/npc/goblin.dm
  code/modules/mob/living/simple_animal/hostile/roguetown/haunt.dm
  modular/Barding/code/Barding_instruments.dm
  stonekeep.dme
Labels: Scheduled for testmerge

#1185 Little maptweaks
  _maps/map_files/roguehamlet/roguehamlet_neu.dmm
  _maps/map_files/templates/dwarf_outpost/Dwarf_Outpost_1.dmm
  _maps/map_files/templates/dwarf_outpost/Dwarf_Outpost_2.dmm
  code/game/objects/effects/spawners/roguemapgen.dm
  code/modules/jobs/job_types/roguetown/nobility/merchant.dm
  code/modules/mob/living/simple_animal/rogue/rogueanimals.dm
  code/modules/roguetown/mapgen/rogueoutdoors.dm
  modular/Mapping/Mapping_aides.dm
  modular/Neu_Farming/code/fermenting_barrel.dm
Labels: Scheduled for testmerge

#1118 Additions, rebalances and new roles
  code/game/objects/items/rogueweapons/melee/swords.dm
  code/game/objects/items/rogueweapons/shields.dm
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/rare/Lmason.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/rare/Lsmith.dm
  code/modules/jobs/job_types/roguetown/garrison/garrisonguard.dm
  code/modules/jobs/job_types/roguetown/other/merc_classes/anthrax.dm
  code/modules/jobs/job_types/roguetown/other/merc_classes/blackoak.dm
  code/modules/jobs/job_types/roguetown/other/merc_classes/boltslinger.dm
  code/modules/jobs/job_types/roguetown/other/merc_classes/grenzelhoft.dm
  code/modules/jobs/job_types/roguetown/other/merc_classes/marauder.dm
  code/modules/jobs/job_types/roguetown/other/merc_classes/steppesman.dm
  code/modules/jobs/job_types/roguetown/other/merc_classes/underdweller.dm
  code/modules/jobs/job_types/roguetown/other/merc_classes/valorian.dm
  code/modules/jobs/job_types/roguetown/other/merc_classes/zybantine.dm
  code/modules/jobs/job_types/roguetown/serfs/blacksmith.dm
  code/modules/jobs/job_types/roguetown/serfs/mason.dm
  icons/roguetown/clothing/armor.dmi
  icons/roguetown/clothing/head.dmi
  icons/roguetown/clothing/onmob/64x64/head.dmi
  icons/roguetown/clothing/onmob/armor.dmi
  icons/roguetown/weapons/32.dmi
  stonekeep.dme
Labels: Merge conflict
