Repository Darkrp-community/OpenKeep, pull requests merged in 2024-07, with the labels that each got.

#260 Trees Burn to Ash[DONE]
  code/_onclick/item_attack.dm
  code/game/objects/items/rogueitems/natural/wood.dm
  code/game/objects/items/rogueweapons/melee/axes.dm
  code/game/objects/items/rogueweapons/rogueweapon.dm
  code/game/objects/structures/roguetown/newtree.dm
  code/modules/mob/living/living_defense.dm
  icons/roguetown/misc/tree.dmi
Labels: scheduled for testmerge

#257 Eoran Acolytes
  code/__DEFINES/roguetown.dm
  code/datums/gods/patrons/divine_pantheon.dm
  code/datums/status_effects/rogue/debuff.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/clothing/rogueclothes/robes.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
  code/modules/jobs/job_types/roguetown/church/monk.dm
  code/modules/roguetown/roguecrafting/weaving.dm
  code/modules/spells/roguetown/acolyte/eora.dm
  icons/roguetown/clothing/armor.dmi
  icons/roguetown/clothing/head.dmi
  icons/roguetown/clothing/neck.dmi
  icons/roguetown/clothing/onmob/armor.dmi
  icons/roguetown/clothing/onmob/helpers/sleeves_armor.dmi
  icons/roguetown/clothing/onmob/neck.dmi
  stonekeep.dme
Labels: scheduled for testmerge

#216 Inhands resprite
  icons/roguetown/weapons/32.dmi
  icons/roguetown/weapons/64.dmi
  icons/roguetown/weapons/tools.dmi
Labels: scheduled for testmerge

#54 Racial Overhaul and able to see other peoples ancestry
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mobs.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/dwarf/dwarfm.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/elf/elfd.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/elf/elfs.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/human/humen.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/other/aasimar.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/other/halfelf.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/other/tiefling.dm
Labels: scheduled for testmerge

#312 Village Elder > Mayor
  _maps/map_files/dakkatown/otherz/dakkaforest.dmm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/rogueitems/keyrings.dm
  code/game/objects/items/rogueitems/keys.dm
  code/modules/jobs/job_types/roguetown/garrison/villagechief.dm
Labels: Map

#299 Minor skill and stat tweaks for Prisoner, Dungeoneer
  code/modules/jobs/job_types/roguetown/garrison/dungeoneer.dm
  code/modules/jobs/job_types/roguetown/peasants/prisoner.dm
Labels: Branch out of date

#337 Hotfix_for_dummyanvil
  _maps/map_files/roguetown/roguetown.dmm
  icons/roguetown/misc/ay.dmi
  modular/Mapping/Mapping_aides.dm
Labels: Ready to merge, Map

#330 Gives Puritan Their Keyring
  code/modules/jobs/job_types/roguetown/church/puritan.dm
Labels: Ready to merge

#301 curtains
  icons/obj/watercloset.dmi
Labels: Icons

#348 Mapping Roguetown Randomizers
  _maps/map_files/roguetown/roguetown.dmm
  _maps/map_files/templates/sk_dungeon/labyrinth_of_xylix.dmm
  code/game/turfs/closed/minerals.dm
  modular/Mapping/Mapping_aides.dm
Labels: Map

#265 More Flaws
  code/_onclick/other_mobs.dm
  code/datums/character_flaw/_character_flaw.dm
  code/datums/character_flaw/addiction.dm
  code/datums/character_flaw/limbloss.dm
  code/datums/stress/negative_events.dm
  code/datums/stress/positive_events.dm
  code/modules/atmospherics/environmental/LINDA_fire.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/emote.dm
  code/modules/reagents/chemistry/reagents/roguetown.dm
  code/modules/surgery/bodyparts/bodypart_dismemberment.dm
Labels: Scheduled for testmerge, Merge conflict

#307 Adds some basic magical rings/circlets for dungeon loot
  code/datums/status_effects/rogue/roguebuff.dm
  code/datums/stress/positive_events.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/rings.dm
  icons/mob/screen_alert.dmi
  icons/roguetown/clothing/head.dmi
  icons/roguetown/clothing/onmob/head.dmi
  icons/roguetown/clothing/rings.dmi
Labels: Squash me

#332 Adjusts Courthouse and Mayor Look
  _maps/map_files/dakkatown/dakkatown.dmm
  code/modules/jobs/job_types/roguetown/garrison/villagechief.dm
Labels: Map, Unapproved restricted changes

#333 zizoid cultist with rituals and thanati bullshit
  code/__DEFINES/role_preferences.dm
  code/__HELPERS/roundend.dm
  code/__HELPERS/unsorted.dm
  code/datums/character_flaw/addiction.dm
  code/datums/stress/negative_events.dm
  code/datums/stress/positive_events.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/roguetown/roguetown.dm
  code/game/objects/effects/decals/cleanable/humans.dm
  code/game/objects/items/clown_items.dm
  code/game/objects/items/rogueitems/magic.dm
  code/game/objects/items/rogueweapons/intents.dm
  code/modules/antagonists/roguetown/villain/vampirelord.dm
  code/modules/antagonists/roguetown/villain/zizocult.dm
  code/modules/events/rogue/_rogue.dm
  code/modules/jobs/job_types/roguetown/church/puritan.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/simple_animal/rogue/creacher/troll.dm
  code/modules/roguetown/roguejobs/fisher/leeches.dm
  code/modules/surgery/organs/ears.dm
  icons/mob/32x64.dmi
  icons/mob/mob.dmi
  icons/obj/sigils.dmi
  icons/roguetown/items/misc.dmi
  icons/roguetown/mob/monster/Trolls.dmi
  sound/music/combatcult.ogg
  sound/vo/cult/praise.ogg
  sound/vo/cult/skvor.ogg
  sound/vo/cult/tesa.ogg
  sound/vo/cult/vs_chant_conj_hf.ogg
  sound/vo/cult/vs_chant_conj_hm.ogg
  sound/vo/cult/vs_chant_conj_lf.ogg
  sound/vo/cult/vs_chant_conj_lm.ogg
  sound/vo/cult/vs_chant_ench_hf.ogg
  sound/vo/cult/vs_chant_ench_hm.ogg
  sound/vo/cult/vs_chant_ench_lf.ogg
  sound/vo/cult/vs_chant_ench_lm.ogg
  sound/vo/cult/vs_chant_evoc_hf.ogg
  sound/vo/cult/vs_chant_evoc_hm.ogg
  sound/vo/cult/vs_chant_evoc_lf.ogg
  sound/vo/cult/vs_chant_evoc_lm.ogg
  sound/vo/cult/vs_chant_illu_hf.ogg
  sound/vo/cult/vs_chant_illu_hm.ogg
  sound/vo/cult/vs_chant_illu_lf.ogg
  sound/vo/cult/vs_chant_illu_lm.ogg
  sound/vo/cult/vs_chant_necr_hf.ogg
  sound/vo/cult/vs_chant_necr_hm.ogg
  sound/vo/cult/vs_chant_necr_lf.ogg
  sound/vo/cult/vs_chant_necr_lm.ogg
  stonekeep.dme
Labels: Scheduled for testmerge, Squash me

#387 Mapping Assets
  code/datums/diseases/anxiety.dm
  code/datums/diseases/magnitis.dm
  code/game/objects/items/candle.dm
  code/game/objects/structures/crates_lockers/roguetown.dm
  code/game/turfs/open/water.dm
  code/modules/reagents/reagent_containers/bottle.dm
  icons/roguetown/items/chairs.dmi
  icons/roguetown/misc/structure.dmi
  icons/roguetown/misc/tables.dmi
  icons/turf/roguefloor.dmi
  modular/Mapping/Mapping_aides.dm
  modular/Mapping/icons/96x96.dmi
  modular/Mapping/icons/decoration.dmi
  modular/Mapping/sound/Folia1490.ogg
  modular/Mapping/sound/Fulminate.ogg
  modular/Mapping/sound/LeTourdion.ogg
Labels: Squash me, Icons

#372 Roguetown bog dungeons
  _maps/map_files/roguetown/otherz/smallswamp.dmm
  _maps/map_files/templates/sk_dungeon/small_bog_dungeon_1.dmm
  _maps/map_files/templates/sk_dungeon/small_bog_dungeon_2.dmm
  _maps/map_files/templates/sk_dungeon/small_bog_dungeon_3.dmm
  _maps/map_files/templates/sk_dungeon/small_bog_dungeon_4.dmm
  _maps/templates/sk_dungeons.dm
  code/modules/mob/living/carbon/human/npc/orc.dm
  code/modules/mob/living/carbon/human/npc/skeleton.dm
Labels: Scheduled for testmerge, Map

#326 Rework Eating and Targeting AI [DONE] [TESTMERGE BEFORE MERGE]
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/retaliate.dm
  code/modules/mob/living/simple_animal/rogue/creacher/bigrat.dm
  code/modules/mob/living/simple_animal/rogue/creacher/bogbug.dm
  code/modules/mob/living/simple_animal/rogue/creacher/honeyspider.dm
  code/modules/mob/living/simple_animal/rogue/creacher/mole.dm
  code/modules/mob/living/simple_animal/rogue/creacher/troll.dm
  code/modules/mob/living/simple_animal/rogue/creacher/trollbog.dm
  code/modules/mob/living/simple_animal/rogue/creacher/volf.dm
  code/modules/mob/living/simple_animal/rogue/farm/goat.dm
  code/modules/mob/living/simple_animal/rogue/game/saiga.dm
  code/modules/mob/living/simple_animal/rogue/rogueanimals.dm
Labels: Scheduled for testmerge

#374 Assassin/hunted
  code/__DEFINES/traits.dm
  code/_onclick/hud/ghost.dm
  code/_onclick/observer.dm
  code/datums/character_flaw/_character_flaw.dm
  code/datums/mind.dm
  code/datums/stress/negative_events.dm
  code/game/objects/items/rogueweapons/melee/knives.dm
  code/modules/clothing/rogueclothes/storage.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/assassin.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/dead/observer/say.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/spells/roguetown/acolyte/necra.dm
  icons/roguetown/weapons/32.dmi
  sound/magic/soulsteal.ogg
Labels: Scheduled for testmerge

#403 Smithing quickfix
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/armor.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
Labels: Bug, Ready to merge

#381 Bugfix (the most terrible)
  code/datums/character_flaw/addiction.dm
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/rings.dm
  code/modules/jobs/job_types/roguetown/nobility/magician.dm
  code/modules/jobs/job_types/roguetown/roguetown.dm
Labels: Scheduled for testmerge

#410 Tiefling hair and tribal cloak
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/cloaks.dm
  code/modules/clothing/rogueclothes/feet.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/bard.dm
  code/modules/jobs/job_types/roguetown/nobility/magician.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/roguetown/roguecrafting/leather.dm
  icons/roguetown/clothing/cloaks.dmi
  icons/roguetown/clothing/feet.dmi
  icons/roguetown/clothing/onmob/cloaks.dmi
  icons/roguetown/clothing/onmob/feet.dmi
  icons/roguetown/mob/hair.dmi
Labels: Icons

#362 Mineral Rework
  code/game/objects/items/rogueitems/natural/stones.dm
  code/game/turfs/closed/minerals.dm
Labels: Unapproved restricted changes

#422 Fix Troll eating Prosthetic Arm Runtime
  code/modules/mob/living/simple_animal/rogue/rogueanimals.dm
Labels: Bug

#367 Unnamed Features PR #367
  _maps/custom/roguehamlet1.dmm
  _maps/map_files/backup2/roguetown.dmm
  _maps/map_files/dakkatown/dakkatown.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/map_files/grimoria/roguetown.dmm
  _maps/map_files/roguetown/otherz/roguehamlet.dmm
  code/__DEFINES/traits.dm
  code/__HELPERS/roundend.dm
  code/_onclick/hud/screen_objects.dm
  code/controllers/subsystem/ticker.dm
  code/game/objects/structures.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/fluff.dm
  code/game/objects/structures/roguetown/redstone.dm
  code/game/objects/structures/roguetown/telescope.dm
  code/game/turfs/open/water.dm
  code/game/turfs/turf.dm
  code/modules/antagonists/roguetown/villain/peasantrebel.dm
  code/modules/cargo/packsrogue/food.dm
  code/modules/cargo/packsrogue/weapons.dm
  code/modules/hydroponics/fermenting_barrel.dm
  code/modules/hydroponics/grown/roguetown.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/dbomb.dm
  code/modules/jobs/job_types/roguetown/nobility/lady.dm
  code/modules/jobs/job_types/roguetown/nobility/lord.dm
  code/modules/jobs/job_types/roguetown/roguetown.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/rogue/creacher/troll.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/reagent_containers/powderspice.dm
  code/modules/roguetown/roguejobs/alchemist/container.dm
  code/modules/roguetown/roguejobs/gravedigger/hole.dm
  icons/mob/32x64.dmi
  sound/misc/roundend.ogg
  stonekeep.dme
Labels: Map

#384 Minor Cooking QOL Changes
  _maps/map_files/roguetown/roguetown.dmm
Labels: Map

#336 Re-adds majority of Merchant roundstart items from Roguetown to Dakkatown
  _maps/map_files/dakkatown/dakkatown.dmm
Labels: Map

#414 Small Tweak to how Monsters Dismember You
  code/modules/mob/living/simple_animal/rogue/rogueanimals.dm
Labels: Scheduled for testmerge

#450 Crown of Darkness and Descriptions for God Helms
  code/modules/clothing/rogueclothes/hats.dm
  icons/roguetown/clothing/onmob/head.dmi
  strings/accent_universal.json
Labels: Icons

#373 Templars
  _maps/map_files/roguetown/roguetown.dmm
  code/__DEFINES/jobs.dm
  code/__DEFINES/roguetown.dm
  code/game/gamemodes/roguetown/roguetown.dm
  code/game/objects/effects/landmarks.dm
  code/modules/clothing/rogueclothes/cloaks.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
  code/modules/jobs/job_types/roguetown/church/confessor.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
  code/modules/jobs/job_types/roguetown/nobility/hand.dm
  code/modules/jobs/jobs.dm
  icons/roguetown/clothing/special/onmob/templar.dmi
  icons/roguetown/clothing/special/tabard_icon.dmi
  icons/roguetown/clothing/special/templar.dmi
  stonekeep.dme
Labels: Scheduled for testmerge, Icons
